# Name of your application. Used to uniquely configure containers.
service: blazor-diffusion

# Name of the container image.
image: netcoreapps/blazordiffusionvue

env:
  clear:
    VIRTUAL_HOST: blazordiffusion.com
    DEPLOY_API: blazordiffusion.com
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: true
  secret:
    - AI_SERVER_APIKEY

# Deploy to these servers.
servers:
  web:
    - 5.78.128.205

# Enable SSL auto certification via Let's Encrypt (and allow for multiple apps on one server).
proxy:
  ssl: true
  host: blazordiffusion.com
  # kamal-proxy connects to your container over port 80, use `app_port` to specify a different port.
  app_port: 8080
  response_timeout: 300

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  server: ghcr.io
  username: 
    - KAMAL_REGISTRY_USERNAME

  # Always use an access token rather than real password (pulled from .kamal/secrets).
  password:
    - KAMAL_REGISTRY_PASSWORD

# Configure builder setup.
builder:
  arch: amd64

volumes:
  - "/opt/docker/BlazorDiffusionVue/App_Data:/app/App_Data"

accessories:
  litestream:
    roles: ["web"]
    image: litestream/litestream
    files: ["config/litestream.yml:/etc/litestream.yml"]
    volumes: ["/opt/docker/BlazorDiffusionVue/App_Data:/data"]
    cmd: replicate
    env:
      secret:
        - R2_ACCESS_KEY_ID
        - R2_SECRET_ACCESS_KEY
