version: "3.9"
services:
    app:
        image: ghcr.io/${IMAGE_REPO}:${RELEASE_VERSION} 
        restart: always
        depends_on:
            - app-litestream
        ports:                                         
            - "8080"                                     
        container_name: ${APP_NAME}_app                
        environment:                                    
            VIRTUAL_HOST: ${HOST_DOMAIN}
            VIRTUAL_PORT: 8080 # New default ASP.NET port -> https://learn.microsoft.com/en-us/dotnet/core/compatibility/containers/8.0/aspnet-port
            LETSENCRYPT_HOST: ${HOST_DOMAIN}           
            LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
            DREAMAI_APIKEY: ${DREAMAI_APIKEY}
            R2_ACCESS_KEY_ID: ${R2_ACCESS_KEY_ID}
            R2_SECRET_ACCESS_KEY: ${R2_SECRET_ACCESS_KEY}
            ASPNETCORE_FORWARDEDHEADERS_ENABLED: true
            AI_SERVER_APIKEY: ${AI_SERVER_APIKEY}
        volumes:
            - ./App_Data:/app/App_Data  
            
    app-litestream:
        container_name: ${APP_NAME}_app_litestream
        image: litestream/litestream
        restart: always
        command: replicate -config /config/litestream.yml
        volumes:
          - ./App_Data:/data
          - ./config:/config
        
    app-restore:
        container_name: ${APP_NAME}_app_litestream_restore
        image: litestream/litestream
        restart: "no"
        profiles:
          - litestream
        command: restore -if-db-not-exists -if-replica-exists -config /assets/litestream.yml /data/db.sqlite
        volumes:
          - ./App_Data:/data
          - ./config:/assets
  
    app-restore-analytics:
        container_name: ${APP_NAME}_app_litestream_analytics
        image: litestream/litestream
        restart: "no"
        profiles:
          - litestream
        command: restore -if-db-not-exists -if-replica-exists -config /assets/litestream.yml /data/analytics.sqlite
        volumes:
          - ./App_Data:/data
          - ./config:/assets

    app-migration:
        image: ghcr.io/${IMAGE_REPO}:${RELEASE_VERSION} 
        restart: "no"                                  
        container_name: ${APP_NAME}_app_migration       
        profiles:                                      
            - migration                                
        command: --AppTasks=migrate                     
        volumes:
            - ./App_Data:/app/App_Data  

networks:
  default:
    external: true                                     
    name: nginx                                                                               
